PROJECT_NAME: deep_q_network
PROJECT_NAME_SHORT: DQN
PATH: ./model/data/
START_FROM: null # null, best, latest
NETWORK_PATH: ./model/data/network.pth
TRAINING_DATA_PATH: ./model/data/training_data.pth
BUFFER_PATH: ./model/data/experience_replay_buffer.pkl
MAX_RUNTIME: 6000 # 100 minutes
CHANNEL_SIZE: 4
ACTION_SIZE: 6
TESTING_FREQUENCY: 40000
ROUNDS_PER_TEST: 30
TEST_SEED: 1234
EXPLORATION_RATE_START: 1.0
EXPLORATION_RATE_MIN: 0.05
# The following parameters are part of a potential sweep
LEARNING_RATE: 0.001
BATCH_SIZE: 32
TRANSFORM_BATCH_RANDOMLY: true
HIDDEN_LAYER_SIZE: 128
NUM_EPOCHS: 1
BUFFER_CAPACITY: 50000
BUFFER_MIN_SIZE: 10000
EXPLORATION_RATE_DECAY: 0.9999995
DISCOUNT_RATE: 0.93
TRAINING_FREQUENCY: 50
TARGET_UPDATE_FREQUENCY: 5000
OPTIMIZER: Adam # Adam, RMSprop, SGD
