VERSION: 32
PROJECT_NAME: classic_sweep
PROJECT_NAME_SHORT: DQN
PATH: ./model/data/
START_FROM: last # null, best, last
USE_ONLY_CNN: false
NETWORK_PATH: ./model/data/network.pth
TRAINING_DATA_PATH: ./model/data/training_data.pth
BUFFER_PATH: ./model/data/experience_replay_buffer.pkl
MAX_RUNTIME: 72000 # 1200 minutes
CHANNEL_SIZE: 6
ACTION_SIZE: 6
ADD_STATE_SIZE: 4
NUM_OPPONENTS: 3
TESTING_FREQUENCY: 40000
ROUNDS_PER_TEST: 50
TEST_SEED: 3456
LOOP_BUFFER_CAPACITY: 15
EXPLORATION_RATE_START: 1.0
EXPLORATION_RATE_MIN: 0.025
PER_PRIORITY_IMPORTANCE: 0.6
PER_WEIGHT_IMPORTANCE_START: 0.4
PER_WEIGHT_IMPORTANCE_MAX: 1.0
PER_WEIGHT_IMPORTANCE_INCREMENT: 0.00000015
# The following parameters are part of a potential sweep
LEARNING_RATE: 0.0001
BATCH_SIZE: 64
USE_DANGER_POTENTIAL: false
TRANSFORM_BATCH_RANDOMLY: false
BREAK_LOOPS: false
USE_DOUBLE_DQN: true
USE_DUELING_DQN: false
USE_PER: true
COIN_IMPORTANCE: 'low'
TD_STEPS: 1
HIDDEN_LAYER_SIZE: 512
NUM_EPOCHS: 3
BUFFER_CAPACITY: 100000
BUFFER_MIN_SIZE: 99990
EXPLORATION_RATE_DECAY: 0.9999995 # IMPORTANT: The exploration rate WAS decreasing slower if it is below 0.3 (REMOVED)
DISCOUNT_RATE: 0.93
TRAINING_FREQUENCY: 60
TARGET_UPDATE_FREQUENCY: 1000
OPTIMIZER: Adam # Adam, RMSprop, SGD
