PROJECT_NAME: deep_q_network
PROJECT_NAME_SHORT: DQN
PATH: ./model/data/
START_FROM: null # null, best, last
NETWORK_PATH: ./model/data/network.pth
TRAINING_DATA_PATH: ./model/data/training_data.pth
BUFFER_PATH: ./model/data/experience_replay_buffer.pkl
MAX_RUNTIME: 28800 # 480 minutes
CHANNEL_SIZE: 5
ACTION_SIZE: 6
TESTING_FREQUENCY: 40000
ROUNDS_PER_TEST: 30
TEST_SEED: 2345
LOOP_BUFFER_CAPACITY: 15
# PRIORITIZED_BUFFER_CAPACITY: 5000
# PRIORITIZED_BUFFER_MIN_SIZE: 1000
# PRIORITIZED_TRAINING_FREQUENCY: 150
EXPLORATION_RATE_START: 1.0
EXPLORATION_RATE_MIN: 0.025
# The following parameters are part of a potential sweep
LEARNING_RATE: 0.001
BATCH_SIZE: 32
USE_DANGER_POTENTIAL: false
TRANSFORM_BATCH_RANDOMLY: false
USE_DOUBLE_DQN: false
TD_STEPS: 1
HIDDEN_LAYER_SIZE: 256
NUM_EPOCHS: 3
BUFFER_CAPACITY: 50000
BUFFER_MIN_SIZE: 10000
EXPLORATION_RATE_DECAY: 0.9999995
DISCOUNT_RATE: 0.93
TRAINING_FREQUENCY: 50
TARGET_UPDATE_FREQUENCY: 5000
OPTIMIZER: Adam # Adam, RMSprop, SGD
