method: random
metric:
  name: test_avg_score
  goal: maximize

parameters:
  LEARNING_RATE:
    values: [0.0001, 0.001, 0.01, 0.1]
  BATCH_SIZE:
    values: [16, 32, 64]
  BUFFER_CAPACITY:
    values: [30000, 50000, 70000]
  BUFFER_MIN_SIZE:
    values: [1000, 10000, 30000]
  EXPLORATION_RATE_DECAY:
    min: 0.999999
    max: 0.9999997
  DISCOUNT_RATE:
    min: 0.9
    max: 0.99
  TRAINING_FREQUENCY:
    values: [50, 100, 200]
  TARGET_UPDATE_FREQUENCY:
    values: [2500, 5000, 10000]
  OPTIMIZER:
    values: ["Adam", "RMSprop"] # Adam, RMSprop, SGD
  START_FROM:  
    value: null # null, best, latest (usually you want to start the sweep from scratch)
project: deep_q_network
command:
  - python
  - main.py
  - play
  - --agents=deep_q_network
  - --train=1
  - --n-rounds=5000
  - --scenario=coin-heaven
  - --no-gui
