method: grid
metric:
  name: test_avg_score
  goal: maximize

parameters:
  LEARNING_RATE:
    value: 0.001
  BATCH_SIZE:
    value: 32
  BUFFER_CAPACITY:
    value: 50000
  BUFFER_MIN_SIZE:
    value: 10000
  HIDDEN_LAYER_SIZE:
    value: 128
  EXPLORATION_RATE_DECAY:
    value: 0.9999995
  DISCOUNT_RATE:
    value: 0.93
  TRAINING_FREQUENCY:
    values: 50
  TARGET_UPDATE_FREQUENCY:
    value: 5000
  OPTIMIZER:
    value: "Adam" # Adam, RMSprop, SGD
  TRANSFORM_BATCH_RANDOMLY:
    values: [false, true]
  NUM_EPOCHS: 
    values: [1, 3]
  START_FROM:  
    value: null # null, best, latest (usually you want to start the sweep from scratch)
project: deep_q_network
command:
  - python
  - main.py
  - play
  - --agents=deep_q_network
  - --train=1
  - --n-rounds=500000
  - --scenario=coin-heaven
  - --no-gui
