method: grid
metric:
  name: test_avg_score
  goal: maximize

parameters:
  TD_STEPS:
    values: [3, 5]
  START_FROM:  
    value: null # null, best, last (usually you want to start the sweep from scratch)
project: deep_q_network
command:
  - python
  - main.py
  - play
  - --agents=deep_q_network
  - --train=1
  - --n-rounds=750000
  - --scenario=loot-crate
  - --no-gui
